# Generated by Django 3.2.12 on 2022-03-28 18:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('phone', models.CharField(max_length=11, unique=True, verbose_name='Telefone')),
            ],
            options={
                'unique_together': {('name', 'phone')},
            },
        ),
        migrations.CreateModel(
            name='DeliveryMan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('phone', models.CharField(max_length=11, unique=True, verbose_name='Telefone')),
                ('vehicle_type', models.CharField(choices=[('CAR', 'Carro'), ('MOTORCYCLE', 'Moto'), ('BIKE', 'Bicicleta')], max_length=15, verbose_name='Tipo do Veículo')),
                ('status', models.CharField(choices=[('IDLE', 'Aguardando'), ('UNAVAILABLE', 'Indisponível'), ('IN_ROUTE', 'Em rota')], default='IDLE', max_length=15, verbose_name='Situação')),
                ('capacity', models.PositiveIntegerField(default=0, verbose_name='Capacidade do Veículo (Nº de pedidos)')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(choices=[('CREDIT_CARD', 'Cartão de Crédito'), ('DEBIT_CARD', 'Cartão de Débito'), ('CASH', 'Dinheiro Vivo'), ('PIX', 'Pix'), ('TED', 'Transferência Bancária')], default='CASH', max_length=20, verbose_name='Método de Pagamento')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Já pago')),
                ('delivery_type', models.CharField(choices=[('DEFAULT', 'Entrega Imediata'), ('PICKUP', 'Retirada no Local')], max_length=20, verbose_name='Tipo de Entrega')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Recebido em')),
                ('modified_on', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
                ('ready_on', models.DateTimeField(blank=True, null=True, verbose_name='Pronto para entrega em')),
                ('finished_on', models.DateTimeField(blank=True, null=True, verbose_name='Concluída em')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='legacy.client', verbose_name='Cliente')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_orders', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='modified_orders', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Produto')),
                ('quantity', models.PositiveIntegerField(verbose_name='Quantidade')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='legacy.order', verbose_name='Ordem')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrderAppointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment', models.DateTimeField(verbose_name='Horário de Entrega')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='legacy.order', verbose_name='Ordem')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
