# Generated by Django 3.2.12 on 2022-04-06 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legacy', '0003_order_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created_on',
            field=models.DateTimeField(auto_now=True, verbose_name='Recebido em'),
        ),
        migrations.AlterField(
            model_name='order',
            name='modified_on',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Modificado em'),
        ),
    ]
