# Generated by Django 3.0.7 on 2022-02-15 19:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('legacy', '0003_auto_20210915_1635'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Nome')),
                ('phone', models.CharField(max_length=11, unique=True, verbose_name='Telefone')),
                ('number', models.PositiveIntegerField(verbose_name='Número')),
                ('street', models.CharField(max_length=100, verbose_name='Rua')),
                ('district', models.CharField(max_length=100, verbose_name='Bairro')),
                ('code', models.CharField(max_length=20, verbose_name='CEP')),
                ('reference', models.CharField(blank=True, max_length=200, null=True, verbose_name='Ponto de Referência')),
                ('country_name', models.CharField(max_length=100, verbose_name='País')),
                ('state_name', models.CharField(max_length=100, verbose_name='Estado')),
                ('city_name', models.CharField(max_length=100, verbose_name='Cidade')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_type', models.CharField(choices=[('DELIVERY', 'Entrega Imediata'), ('PICKUP', 'Retirada no Local')], max_length=20, verbose_name='Tipo de Entrega')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Recebido em')),
                ('modified_on', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
                ('finished_on', models.DateTimeField(blank=True, null=True, verbose_name='Concluída em')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='legacy.Client', verbose_name='Cliente')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_orders', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='modified_orders', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Produto')),
                ('quantity', models.PositiveIntegerField(verbose_name='Quantidade')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='legacy.Order', verbose_name='Ordem')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrderAppointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment', models.DateTimeField(verbose_name='Horário de Entrega')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='legacy.Order', verbose_name='Ordem')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
