# Generated by Django 3.2.12 on 2022-05-18 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legacy', '0004_auto_20220406_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_esperado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Pagamento Recebido'),
        ),
        migrations.AddField(
            model_name='order',
            name='total_pedido',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total Pedido'),
        ),
        migrations.AddField(
            model_name='order',
            name='valor_troco',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Troco Devolvido'),
        ),
    ]
