# Generated by Django 3.0.7 on 2022-02-21 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legacy', '0006_deliveryman'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryman',
            name='capacity',
            field=models.PositiveIntegerField(default=0, verbose_name='Capacidade do Veículo (Nº de pedidos)'),
        ),
    ]
