# Generated by Django 3.2.12 on 2022-05-19 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('legacy', '0006_auto_20220519_1035'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='valor_troco',
            new_name='change',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='total_esperado',
            new_name='payment',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='total_pedido',
            new_name='total_value',
        ),
    ]
