# Generated by Django 3.2.12 on 2022-05-20 15:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('legacy', '0007_auto_20220519_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='accounts.user', verbose_name='Criado por'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deliveryman',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='accounts.user', verbose_name='Criado por'),
            preserve_default=False,
        ),
    ]
