# Generated by Django 3.0.7 on 2022-02-22 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legacy', '0007_deliveryman_capacity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deliveryman',
            old_name='vehycle_type',
            new_name='vehicle_type',
        ),
        migrations.AlterField(
            model_name='deliveryman',
            name='status',
            field=models.CharField(choices=[('IDLE', 'Aguardando'), ('UNAVAILABLE', 'Indisponível'), ('IN_ROUTE', 'Em rota')], default='IDLE', max_length=15, verbose_name='Situação'),
        ),
    ]
