# Generated by Django 3.0.7 on 2022-03-02 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legacy', '0008_auto_20220222_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ready_on',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Pronto para entrega em'),
        ),
    ]
