# Generated by Django 3.0.7 on 2022-03-02 18:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('legacy', '0009_order_ready_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_type',
            field=models.CharField(choices=[('DEFAULT', 'Entrega Imediata'), ('PICKUP', 'Retirada no Local')], max_length=20, verbose_name='Tipo de Entrega'),
        ),
        migrations.AlterField(
            model_name='order',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='modified_orders', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por'),
        ),
    ]
