# Generated by Django 3.0.7 on 2022-03-03 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legacy', '0011_auto_20220302_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='Já pago'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('CREDIT_CARD', 'Cartão de Crédito'), ('DEBIT_CARD', 'Cartão de Débito'), ('CASH', 'Dinheiro Vivo'), ('PIX', 'Pix'), ('TED', 'Transferência Bancária')], default='CASH', max_length=20, verbose_name='Método de Pagamento'),
        ),
    ]
