# Generated by Django 3.0.7 on 2022-03-21 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legacy', '0013_auto_20220317_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='country',
            field=models.CharField(default='Brasil', max_length=200, verbose_name='País'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='branch',
            name='state',
            field=models.CharField(default='Minas Gerais', max_length=200, verbose_name='Estado'),
            preserve_default=False,
        ),
    ]
