# Generated by Django 3.2.12 on 2022-03-22 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legacy', '0015_auto_20220322_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientaddress',
            name='created_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
