# Generated by Django 3.2.12 on 2022-03-22 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legacy', '0016_clientaddress_created_on'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientaddress',
            options={'ordering': ['-created_on']},
        ),
        migrations.AddField(
            model_name='clientaddress',
            name='altitude',
            field=models.DecimalField(decimal_places=16, default=0, max_digits=22),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientaddress',
            name='latitude',
            field=models.DecimalField(decimal_places=16, default=0, max_digits=22),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientaddress',
            name='longitude',
            field=models.DecimalField(decimal_places=16, default=0, max_digits=22),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='client',
            unique_together={('name', 'phone')},
        ),
        migrations.AlterUniqueTogether(
            name='clientaddress',
            unique_together={('client', 'street', 'number')},
        ),
    ]
