# Generated by Django 3.2.12 on 2022-03-28 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('legacy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=100, verbose_name='País')),
                ('state_name', models.CharField(max_length=100, verbose_name='Estado')),
                ('city_name', models.CharField(max_length=100, verbose_name='Cidade')),
                ('number', models.PositiveIntegerField(verbose_name='Número')),
                ('street', models.CharField(max_length=100, verbose_name='Rua')),
                ('district', models.CharField(max_length=100, verbose_name='Bairro')),
                ('code', models.CharField(max_length=20, verbose_name='CEP')),
                ('reference', models.CharField(blank=True, max_length=200, null=True, verbose_name='Ponto de Referência')),
                ('latitude', models.DecimalField(decimal_places=16, max_digits=22)),
                ('longitude', models.DecimalField(decimal_places=16, max_digits=22)),
                ('altitude', models.DecimalField(decimal_places=16, max_digits=22)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClientAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=100, verbose_name='País')),
                ('state_name', models.CharField(max_length=100, verbose_name='Estado')),
                ('city_name', models.CharField(max_length=100, verbose_name='Cidade')),
                ('number', models.PositiveIntegerField(verbose_name='Número')),
                ('street', models.CharField(max_length=100, verbose_name='Rua')),
                ('district', models.CharField(max_length=100, verbose_name='Bairro')),
                ('code', models.CharField(max_length=20, verbose_name='CEP')),
                ('reference', models.CharField(blank=True, max_length=200, null=True, verbose_name='Ponto de Referência')),
                ('latitude', models.DecimalField(decimal_places=16, max_digits=22)),
                ('longitude', models.DecimalField(decimal_places=16, max_digits=22)),
                ('altitude', models.DecimalField(decimal_places=16, max_digits=22)),
                ('active', models.BooleanField(default=True)),
                ('distance', models.FloatField(verbose_name='Distância (KM)')),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='legacy.client')),
            ],
            options={
                'ordering': ['-active', '-created_on'],
                'unique_together': {('client', 'street', 'number')},
            },
        ),
    ]
