# Generated by Django 3.2.12 on 2022-03-29 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='altitude',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='branch',
            name='latitude',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='branch',
            name='longitude',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='clientaddress',
            name='altitude',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='clientaddress',
            name='latitude',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='clientaddress',
            name='longitude',
            field=models.CharField(max_length=20),
        ),
    ]
