# Generated by Django 3.0.7 on 2022-03-21 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routing', '0002_city'),
    ]

    operations = [
        migrations.DeleteModel(
            name='City',
        ),
    ]
